### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by illtellyoulater** [yfszzx/stable-diffusion-webui-inspiration#11]
I git pulled the extension from this repository and checked the Inspiration tab was present in the web-ui, then I went to the txt2img tab > scripts > "create inspiration images" and hit the Generate button, but this is what I got:

```
Error completing request
Arguments: ('', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 10, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, False, False, None, '', '', '', False, 4.0, '', 10.0, False, False, True, 30.0, True, False, False, False, 1, '', 0, '', True, True, False, 1.0, 2.0, 'a painting in', 'style', 'picture frame, portrait photo', None) {}
Traceback (most recent call last):
  File "C:\Users\username\Downloads\generative-nn-models\stable-diffusion-webui\modules\ui.py", line 221, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\username\Downloads\generative-nn-models\stable-diffusion-webui\webui.py", line 63, in f
    res = func(*args, **kwargs)
  File "C:\Users\username\Downloads\generative-nn-models\stable-diffusion-webui\modules\txt2img.py", line 45, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\Users\username\Downloads\generative-nn-models\stable-diffusion-webui\modules\scripts.py", line 286, in run
    processed = script.run(p, *script_args)
  File "C:\Users\username\Downloads\generative-nn-models\stable-diffusion-webui\extensions\stable-diffusion-webui-inspiration\scripts\inspiration.py", line 39, in run
    for file in files:
TypeError: 'NoneType' object is not iterable
```

What am I doing wrong?

**Comment by luminouspear** [comment]
This happens to me when I forget to upload a file for iteration

**Comment by illtellyoulater** [comment]
@luminouspear I see, but what file should I upload? I don't think this is written in the instructions?

**Comment by yfszzx** [comment]
> @luminouspear I see, but what file should I upload? I don't think this is written in the instructions?
All the pictures are created by a script named "Create inspiration images" in the txt2img page and the artist's and genre's names come from the following repository: https://github.com/pharmapsychotic/clip-interrogator/tree/main/data

**Comment by illtellyoulater** [comment]
@yfszzx did you actually read my initial comment?
