### ISSUE TITLE
Click inspiration image after error

### ISSUE THREAD

**Issue by chouhai2018** [yfszzx/stable-diffusion-webui-inspiration#41]
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1159, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1146, in validate_inputs
    raise ValueError(
ValueError: An event handler (select_click) didn't receive enough input values (needed: 2, got: 1).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [textbox, state]
Received inputs:
    ["NaN"]

use dataset
(https://huggingface.co/datasets/yfszzx/inspiration/blob/main/inspiration.zip)

Microsoft Edge
版本 113.0.1774.57 (正式版本) (64 位)

**Comment by tolerance-go** [comment]
same me
