### ISSUE TITLE
Create inspiration images script not working

### ISSUE THREAD

**Issue by schoenid** [yfszzx/stable-diffusion-webui-inspiration#42]
Installed like proposed:
![image](https://github.com/yfszzx/stable-diffusion-webui-inspiration/assets/15383666/af97c0c1-99ab-4be0-a092-ba8faba88f77)

Content of the file "artist.txt":
![image](https://github.com/yfszzx/stable-diffusion-webui-inspiration/assets/15383666/f8b50272-4921-4d5a-8a5f-fbd5bd4a50c5)

Loading script:
![image](https://github.com/yfszzx/stable-diffusion-webui-inspiration/assets/15383666/ca1e320a-b3aa-4904-a696-7eb013eaa0eb)

Result:
```
TypeError: Script.run() missing 2 required positional arguments: 'prompt_placeholder' and 'files'
Time taken: 0.0 sec.
```

`readme.md` with:

> - Run the "Create inspiration images" script inside the "txt2img" page to create images.

Does not tell how ... using the "Generate" button?

> [Look here for more install details](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions)

does not really tell me more about the installation.
I do know now, something is missing. But what exactly and where?
'prompt_placeholder' and 'files' are defined in the script placeholders. So why this error?

**Comment by schoenid** [comment]
After a manual download and copying the files to `.../stable-diffusion-webui/extensions/stable-diffusion-webui-inspiration/inspiration/` it looks fine, but after a click or two there are errors:
![image](https://github.com/yfszzx/stable-diffusion-webui-inspiration/assets/15383666/2455a6d7-003a-4e58-8b7f-b625ed44528f)

Console:
```
Traceback (most recent call last):
  File "/home/sd/Tech/Linux/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/sd/Tech/Linux/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/sd/Tech/Linux/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1222, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "/home/sd/Tech/Linux/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1209, in validate_inputs
    raise ValueError(
ValueError: An event handler (select_click) didn't receive enough input values (needed: 2, got: 1).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [textbox, state]
Received inputs:
    ["NaN"]
```

The extension is unusable.

System information:
Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.2.0-1014-lowlatency (64-bit)
Graphics Platform: X11
Processors: 16 × 13th Gen Intel® Core™ i7-13700K
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060/PCIe/SSE2
